I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 37, in script
    with disolve
  File "game/script.rpy", line 37, in <module>
    with disolve
NameError: name 'disolve' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 37, in script
    with disolve
  File "/Applications/renpy-6.99.5-sdk/renpy/ast.py", line 1243, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Applications/renpy-6.99.5-sdk/renpy/python.py", line 1482, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 37, in <module>
    with disolve
NameError: name 'disolve' is not defined

Darwin-14.0.0-x86_64-i386-64bit
Ren'Py 6.99.5.602
The Doorman 0.0
